package ru.exlmoto.jiconcreator;

import javax.swing.*;

import java.awt.*;
import java.awt.event.WindowEvent;

import java.net.URI;

import java.util.ResourceBundle;

/**
 *
 * @author exl
 */
public class JIconCreatorAbout extends javax.swing.JDialog {

    private boolean openUrl(String url) {
        ResourceBundle bundle = ResourceBundle.getBundle("Bundle");
        if (Desktop.isDesktopSupported()) {
            Desktop desktop = Desktop.getDesktop();
            try {
                desktop.browse(URI.create(url));
                return true;
            } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(null,
                        bundle.getString("JIconCreatorAbout.errorLink.text"),
                        bundle.getString("JIconCreatorAbout.errorLink.title"),
                        JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null,
                    bundle.getString("JIconCreatorAbout.errorLink.text"),
                    bundle.getString("JIconCreatorAbout.errorLink.title"),
                    JOptionPane.ERROR_MESSAGE);
        }
        return false;
    }

    private void closeDialogWindow() {
        processWindowEvent(new WindowEvent(JIconCreatorAbout.this, WindowEvent.WINDOW_CLOSING));
    }

    /**
     * Creates new form JIconCreatorAbout
     */
    public JIconCreatorAbout(java.awt.Frame parent, boolean modal) {
        super(parent, modal);

        initComponents();

        jButtonAboutClose.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabelAboutIcon = new javax.swing.JLabel();
        jLabelNameA = new javax.swing.JLabel();
        jLabelVersionA = new javax.swing.JLabel();
        jLabelDescA = new javax.swing.JLabel();
        jLabelCopyrightSignA = new javax.swing.JLabel();
        jLabelLicenseA = new javax.swing.JLabel();
        jLabelLinksA = new javax.swing.JLabel();
        jButtonAboutClose = new javax.swing.JButton();
        jButtonExlmoto = new javax.swing.JButton();
        jButtonGithub = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("Bundle"); // NOI18N
        setTitle(bundle.getString("JIconCreatorAbout.title")); // NOI18N
        setMaximumSize(new java.awt.Dimension(265, 345));
        setMinimumSize(new java.awt.Dimension(265, 345));
        setName("aboutDialog"); // NOI18N
        setPreferredSize(new java.awt.Dimension(265, 345));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jLabelAboutIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/app_icon.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        getContentPane().add(jLabelAboutIcon, gridBagConstraints);

        jLabelNameA.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelNameA.setText(bundle.getString("JIconCreatorAbout.jLabelNameA.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        getContentPane().add(jLabelNameA, gridBagConstraints);

        jLabelVersionA.setText(bundle.getString("JIconCreatorAbout.jLabelVersionA.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        getContentPane().add(jLabelVersionA, gridBagConstraints);

        jLabelDescA.setText(bundle.getString("JIconCreatorAbout.jLabelDescA.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(15, 0, 15, 0);
        getContentPane().add(jLabelDescA, gridBagConstraints);

        jLabelCopyrightSignA.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        jLabelCopyrightSignA.setText(bundle.getString("JIconCreatorAbout.jLabelCopyrightSignA.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        getContentPane().add(jLabelCopyrightSignA, gridBagConstraints);

        jLabelLicenseA.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        jLabelLicenseA.setText(bundle.getString("JIconCreatorAbout.jLabelLicenseA.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 15, 0);
        getContentPane().add(jLabelLicenseA, gridBagConstraints);

        jLabelLinksA.setText(bundle.getString("JIconCreatorAbout.jLabelLinksA.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 3, 0, 3);
        getContentPane().add(jLabelLinksA, gridBagConstraints);

        jButtonAboutClose.setText(bundle.getString("JIconCreatorAbout.jButtonAboutClose.text")); // NOI18N
        jButtonAboutClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAboutCloseActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LAST_LINE_END;
        getContentPane().add(jButtonAboutClose, gridBagConstraints);

        jButtonExlmoto.setForeground(new java.awt.Color(0, 0, 204));
        jButtonExlmoto.setText(bundle.getString("JIconCreatorAbout.jButtonExlmoto.text")); // NOI18N
        jButtonExlmoto.setToolTipText(bundle.getString("JIconCreatorAbout.jButtonExlmoto.toolTipText")); // NOI18N
        jButtonExlmoto.setBorderPainted(false);
        jButtonExlmoto.setContentAreaFilled(false);
        jButtonExlmoto.setMargin(new java.awt.Insets(2, 0, 2, 0));
        jButtonExlmoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExlmotoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        getContentPane().add(jButtonExlmoto, gridBagConstraints);

        jButtonGithub.setForeground(new java.awt.Color(0, 0, 204));
        jButtonGithub.setText(bundle.getString("JIconCreatorAbout.jButtonGithub.text")); // NOI18N
        jButtonGithub.setToolTipText(bundle.getString("JIconCreatorAbout.jButtonGithub.toolTipText")); // NOI18N
        jButtonGithub.setBorderPainted(false);
        jButtonGithub.setContentAreaFilled(false);
        jButtonGithub.setMargin(new java.awt.Insets(2, 0, 2, 0));
        jButtonGithub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGithubActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        getContentPane().add(jButtonGithub, gridBagConstraints);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonExlmotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExlmotoActionPerformed
        if (openUrl(jButtonExlmoto.getToolTipText())) {
            closeDialogWindow();
        }
    }//GEN-LAST:event_jButtonExlmotoActionPerformed

    private void jButtonGithubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGithubActionPerformed
        if (openUrl(jButtonGithub.getToolTipText())) {
            closeDialogWindow();
        }
    }//GEN-LAST:event_jButtonGithubActionPerformed

    private void jButtonAboutCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAboutCloseActionPerformed
        closeDialogWindow();
    }//GEN-LAST:event_jButtonAboutCloseActionPerformed

    public void showAboutDialog() {
        /* Display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAboutClose;
    private javax.swing.JButton jButtonExlmoto;
    private javax.swing.JButton jButtonGithub;
    private javax.swing.JLabel jLabelAboutIcon;
    private javax.swing.JLabel jLabelCopyrightSignA;
    private javax.swing.JLabel jLabelDescA;
    private javax.swing.JLabel jLabelLicenseA;
    private javax.swing.JLabel jLabelLinksA;
    private javax.swing.JLabel jLabelNameA;
    private javax.swing.JLabel jLabelVersionA;
    // End of variables declaration//GEN-END:variables
}
