/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ru.exlmoto.jiconcreator;

/**
 *
 * @author exl
 */
public class JIconCreatorAbout extends javax.swing.JDialog {

    /**
     * Creates new form JIconCreatorAbout
     */
    public JIconCreatorAbout(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabelAboutIcon = new javax.swing.JLabel();
        jLabelNameA = new javax.swing.JLabel();
        jLabelVersionA = new javax.swing.JLabel();
        jLabelDescA = new javax.swing.JLabel();
        jLabelCopyrightSignA = new javax.swing.JLabel();
        jLabelLicenseA = new javax.swing.JLabel();
        jLabelLinksA = new javax.swing.JLabel();
        jButtonAboutClose = new javax.swing.JButton();
        jButtonExlmoto = new javax.swing.JButton();
        jButtonGithub = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(245, 330));
        setMinimumSize(new java.awt.Dimension(245, 330));
        setPreferredSize(new java.awt.Dimension(245, 330));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jLabelAboutIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/app_icon.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        getContentPane().add(jLabelAboutIcon, gridBagConstraints);

        jLabelNameA.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelNameA.setText("JIconCreator");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        getContentPane().add(jLabelNameA, gridBagConstraints);

        jLabelVersionA.setText("v1.0 | 25-APR-2019");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        getContentPane().add(jLabelVersionA, gridBagConstraints);

        jLabelDescA.setText("<html><body><center>Improved icon-making program<br>that was used in the<br>Android ADT plugin for Eclipse.</center></body></html>");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(15, 0, 15, 0);
        getContentPane().add(jLabelDescA, gridBagConstraints);

        jLabelCopyrightSignA.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        jLabelCopyrightSignA.setText("(C) EXL, 2019");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        getContentPane().add(jLabelCopyrightSignA, gridBagConstraints);

        jLabelLicenseA.setFont(new java.awt.Font("Dialog", 3, 12)); // NOI18N
        jLabelLicenseA.setText("License: Apache 2.0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 15, 0);
        getContentPane().add(jLabelLicenseA, gridBagConstraints);

        jLabelLinksA.setText("Links:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 3, 0, 3);
        getContentPane().add(jLabelLinksA, gridBagConstraints);

        jButtonAboutClose.setText("Close");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LAST_LINE_END;
        getContentPane().add(jButtonAboutClose, gridBagConstraints);

        jButtonExlmoto.setForeground(new java.awt.Color(0, 0, 204));
        jButtonExlmoto.setText("exlmoto.ru");
        jButtonExlmoto.setToolTipText("https://exlmoto.ru/new-updates-and-tools-2/#jiconcreator");
        jButtonExlmoto.setBorderPainted(false);
        jButtonExlmoto.setContentAreaFilled(false);
        jButtonExlmoto.setFocusPainted(false);
        jButtonExlmoto.setMargin(new java.awt.Insets(2, 0, 2, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        getContentPane().add(jButtonExlmoto, gridBagConstraints);

        jButtonGithub.setForeground(new java.awt.Color(0, 0, 204));
        jButtonGithub.setText("github.com");
        jButtonGithub.setToolTipText("https://github.com/EXL/JIconCreator");
        jButtonGithub.setBorderPainted(false);
        jButtonGithub.setContentAreaFilled(false);
        jButtonGithub.setFocusPainted(false);
        jButtonGithub.setMargin(new java.awt.Insets(2, 0, 2, 0));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        getContentPane().add(jButtonGithub, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void showAboutDialog() {
        /* Display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAboutClose;
    private javax.swing.JButton jButtonExlmoto;
    private javax.swing.JButton jButtonGithub;
    private javax.swing.JLabel jLabelAboutIcon;
    private javax.swing.JLabel jLabelCopyrightSignA;
    private javax.swing.JLabel jLabelDescA;
    private javax.swing.JLabel jLabelLicenseA;
    private javax.swing.JLabel jLabelLinksA;
    private javax.swing.JLabel jLabelNameA;
    private javax.swing.JLabel jLabelVersionA;
    // End of variables declaration//GEN-END:variables
}
