/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ru.exlmoto.jiconcreator;

import com.android.assetstudiolib.GraphicGenerator;

import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowEvent;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.util.Iterator;

/**
 *
 * @author exl
 */
public class JIconCreatorClipart extends javax.swing.JDialog {

    /**
     * Creates new form JIconCreatorClipart
     */
    public JIconCreatorClipart(JIconCreatorGui parent, boolean modal,
                               JIconCreatorGlue glue, JIconCreatorOptions options) {
        super(parent, modal);
        initComponents();

        try {
            Iterator<String> clipartNames = GraphicGenerator.getClipartNames();
            while (clipartNames.hasNext()) {
                String name = clipartNames.next();
                BufferedImage buttonIcon = glue.getClipartImage(name, false);
                JButton button = new JButton(new ImageIcon(buttonIcon));
                button.setBorderPainted(false);
                button.setContentAreaFilled(false);
                button.addActionListener(new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent e) {
                        options.setClipartName(name);
                        parent.updatePreviewIcons();

                        processWindowEvent(new WindowEvent(JIconCreatorClipart.this, WindowEvent.WINDOW_CLOSING));
                    }
                });
                jPanelClipart.add(button);
                if (options.getClipartName().equals(name)) {
                    button.requestFocus();
                }
            }
        } catch (IOException ioe) {
            ioe.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanelClipart = new javax.swing.JPanel();
        jButtonClipartClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanelClipart.setMaximumSize(new java.awt.Dimension(800, 600));
        jPanelClipart.setMinimumSize(new java.awt.Dimension(800, 600));
        jPanelClipart.setPreferredSize(new java.awt.Dimension(800, 600));
        jPanelClipart.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 0));
        getContentPane().add(jPanelClipart, new java.awt.GridBagConstraints());

        jButtonClipartClose.setText("Close");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        getContentPane().add(jButtonClipartClose, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void showCliparDialog() {
        /* Display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.gc();
                    }
                });
                setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonClipartClose;
    private javax.swing.JPanel jPanelClipart;
    // End of variables declaration//GEN-END:variables
}
