/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ru.exlmoto.jiconcreator;

/**
 *
 * @author exl
 */
public class JIconCreator extends javax.swing.JFrame {

    /**
     * Creates new form JIconCreator
     */
    public JIconCreator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane = new javax.swing.JSplitPane();
        jPanelPreview = new javax.swing.JPanel();
        jLabelMdpiL = new javax.swing.JLabel();
        jLabelMdpiI = new javax.swing.JLabel();
        jLabelHdpiL = new javax.swing.JLabel();
        jLabelHdpiI = new javax.swing.JLabel();
        jLabelXhdpiL = new javax.swing.JLabel();
        jLabelXhdpiI = new javax.swing.JLabel();
        jLabelXxhdpiL = new javax.swing.JLabel();
        jLabelXxhdpiI = new javax.swing.JLabel();
        jPanelGeneral = new javax.swing.JPanel();
        jTabbedPane = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanelStatusBar = new javax.swing.JPanel();
        fillerSmallH1 = new javax.swing.Box.Filler(new java.awt.Dimension(3, 0), new java.awt.Dimension(3, 0), new java.awt.Dimension(3, 32767));
        jLabelStatusBar = new javax.swing.JLabel();
        fillerLargeH1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jButtonSave = new javax.swing.JButton();
        fillerSmallH2 = new javax.swing.Box.Filler(new java.awt.Dimension(3, 0), new java.awt.Dimension(3, 0), new java.awt.Dimension(3, 32767));
        jButtonSaveAs = new javax.swing.JButton();
        fillerSmallH3 = new javax.swing.Box.Filler(new java.awt.Dimension(3, 0), new java.awt.Dimension(3, 0), new java.awt.Dimension(3, 32767));
        jButtonPreview = new javax.swing.JButton();
        jMenuBar = new javax.swing.JMenuBar();
        jMenuFile = new javax.swing.JMenu();
        jMenuItemPreview = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItemSave = new javax.swing.JMenuItem();
        jMenuItemSaveAs = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItemExit = new javax.swing.JMenuItem();
        jMenuStyle = new javax.swing.JMenu();
        jMenuHelp = new javax.swing.JMenu();
        jMenuItemAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("Bundle"); // NOI18N
        setTitle(bundle.getString("JIconCreator.title")); // NOI18N
        setPreferredSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jSplitPane.setDividerLocation(550);

        jPanelPreview.setMinimumSize(new java.awt.Dimension(150, 600));
        jPanelPreview.setLayout(new javax.swing.BoxLayout(jPanelPreview, javax.swing.BoxLayout.PAGE_AXIS));

        jLabelMdpiL.setText(bundle.getString("JIconCreator.jLabelMdpiL.text")); // NOI18N
        jPanelPreview.add(jLabelMdpiL);

        jLabelMdpiI.setText(bundle.getString("JIconCreator.jLabelMdpiI.text")); // NOI18N
        jPanelPreview.add(jLabelMdpiI);

        jLabelHdpiL.setText(bundle.getString("JIconCreator.jLabelHdpiL.text")); // NOI18N
        jPanelPreview.add(jLabelHdpiL);

        jLabelHdpiI.setText(bundle.getString("JIconCreator.jLabelHdpiI.text")); // NOI18N
        jPanelPreview.add(jLabelHdpiI);

        jLabelXhdpiL.setText(bundle.getString("JIconCreator.jLabelXhdpiL.text")); // NOI18N
        jPanelPreview.add(jLabelXhdpiL);

        jLabelXhdpiI.setText(bundle.getString("JIconCreator.jLabelXhdpiI.text")); // NOI18N
        jPanelPreview.add(jLabelXhdpiI);

        jLabelXxhdpiL.setText(bundle.getString("JIconCreator.jLabelXxhdpiL.text")); // NOI18N
        jPanelPreview.add(jLabelXxhdpiL);

        jLabelXxhdpiI.setText(bundle.getString("JIconCreator.jLabelXxhdpiI.text")); // NOI18N
        jPanelPreview.add(jLabelXxhdpiI);

        jSplitPane.setRightComponent(jPanelPreview);

        jPanelGeneral.setLayout(new javax.swing.BoxLayout(jPanelGeneral, javax.swing.BoxLayout.PAGE_AXIS));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 544, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 520, Short.MAX_VALUE)
        );

        jTabbedPane.addTab(bundle.getString("JIconCreator.jPanel1.TabConstraints.tabTitle"), jPanel1); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 544, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 520, Short.MAX_VALUE)
        );

        jTabbedPane.addTab(bundle.getString("JIconCreator.jPanel2.TabConstraints.tabTitle"), jPanel2); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 544, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 520, Short.MAX_VALUE)
        );

        jTabbedPane.addTab(bundle.getString("JIconCreator.jPanel3.TabConstraints.tabTitle"), jPanel3); // NOI18N

        jPanelGeneral.add(jTabbedPane);

        jPanelStatusBar.setMaximumSize(new java.awt.Dimension(800, 30));
        jPanelStatusBar.setMinimumSize(new java.awt.Dimension(400, 30));
        jPanelStatusBar.setPreferredSize(new java.awt.Dimension(550, 30));
        jPanelStatusBar.setLayout(new javax.swing.BoxLayout(jPanelStatusBar, javax.swing.BoxLayout.LINE_AXIS));
        jPanelStatusBar.add(fillerSmallH1);

        jLabelStatusBar.setText(bundle.getString("JIconCreator.jLabelStatusBar.text")); // NOI18N
        jPanelStatusBar.add(jLabelStatusBar);
        jPanelStatusBar.add(fillerLargeH1);

        jButtonSave.setText(bundle.getString("JIconCreator.jButtonSave.text")); // NOI18N
        jPanelStatusBar.add(jButtonSave);
        jPanelStatusBar.add(fillerSmallH2);

        jButtonSaveAs.setText(bundle.getString("JIconCreator.jButtonSaveAs.text")); // NOI18N
        jPanelStatusBar.add(jButtonSaveAs);
        jPanelStatusBar.add(fillerSmallH3);

        jButtonPreview.setText(bundle.getString("JIconCreator.jButtonPreview.text")); // NOI18N
        jPanelStatusBar.add(jButtonPreview);

        jPanelGeneral.add(jPanelStatusBar);

        jSplitPane.setLeftComponent(jPanelGeneral);

        getContentPane().add(jSplitPane);

        jMenuFile.setText(bundle.getString("JIconCreator.jMenuFile.text")); // NOI18N

        jMenuItemPreview.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemPreview.setText(bundle.getString("JIconCreator.jMenuItemPreview.text")); // NOI18N
        jMenuFile.add(jMenuItemPreview);
        jMenuFile.add(jSeparator1);

        jMenuItemSave.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemSave.setText(bundle.getString("JIconCreator.jMenuItemSave.text")); // NOI18N
        jMenuFile.add(jMenuItemSave);

        jMenuItemSaveAs.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemSaveAs.setText(bundle.getString("JIconCreator.jMenuItemSaveAs.text")); // NOI18N
        jMenuFile.add(jMenuItemSaveAs);
        jMenuFile.add(jSeparator2);

        jMenuItemExit.setText(bundle.getString("JIconCreator.jMenuItemExit.text")); // NOI18N
        jMenuFile.add(jMenuItemExit);

        jMenuBar.add(jMenuFile);

        jMenuStyle.setText(bundle.getString("JIconCreator.jMenuStyle.text")); // NOI18N
        jMenuBar.add(jMenuStyle);

        jMenuHelp.setText(bundle.getString("JIconCreator.jMenuHelp.text")); // NOI18N

        jMenuItemAbout.setText(bundle.getString("JIconCreator.jMenuItemAbout.text")); // NOI18N
        jMenuHelp.add(jMenuItemAbout);

        jMenuBar.add(jMenuHelp);

        setJMenuBar(jMenuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JIconCreator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JIconCreator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JIconCreator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JIconCreator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JIconCreator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler fillerLargeH1;
    private javax.swing.Box.Filler fillerSmallH1;
    private javax.swing.Box.Filler fillerSmallH2;
    private javax.swing.Box.Filler fillerSmallH3;
    private javax.swing.JButton jButtonPreview;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JButton jButtonSaveAs;
    private javax.swing.JLabel jLabelHdpiI;
    private javax.swing.JLabel jLabelHdpiL;
    private javax.swing.JLabel jLabelMdpiI;
    private javax.swing.JLabel jLabelMdpiL;
    private javax.swing.JLabel jLabelStatusBar;
    private javax.swing.JLabel jLabelXhdpiI;
    private javax.swing.JLabel jLabelXhdpiL;
    private javax.swing.JLabel jLabelXxhdpiI;
    private javax.swing.JLabel jLabelXxhdpiL;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenu jMenuFile;
    private javax.swing.JMenu jMenuHelp;
    private javax.swing.JMenuItem jMenuItemAbout;
    private javax.swing.JMenuItem jMenuItemExit;
    private javax.swing.JMenuItem jMenuItemPreview;
    private javax.swing.JMenuItem jMenuItemSave;
    private javax.swing.JMenuItem jMenuItemSaveAs;
    private javax.swing.JMenu jMenuStyle;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelGeneral;
    private javax.swing.JPanel jPanelPreview;
    private javax.swing.JPanel jPanelStatusBar;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JSplitPane jSplitPane;
    private javax.swing.JTabbedPane jTabbedPane;
    // End of variables declaration//GEN-END:variables
}
