package ru.exlmoto.jiconcreator;

import javax.swing.*;

import java.awt.event.WindowEvent;
import java.awt.image.BufferedImage;

/**
 *
 * @author exl
 */
public class JIconCreatorPreview extends javax.swing.JDialog {

    /**
     * Creates new form JIconCreatorPreview
     */
    public JIconCreatorPreview(java.awt.Frame parent, boolean modal, BufferedImage[] previews) {
        super(parent, modal);
        initComponents();

        jLabelPreviewWebI.setIcon(new ImageIcon(previews[1]));
        jLabelPreviewHdpiI.setIcon(new ImageIcon(previews[0]));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabelPreviewHidpiL = new javax.swing.JLabel();
        jLabelPreviewWebL = new javax.swing.JLabel();
        jLabelPreviewHdpiI = new javax.swing.JLabel();
        jLabelPreviewWebI = new javax.swing.JLabel();
        jButtonClosePreview = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("Bundle"); // NOI18N
        setTitle(bundle.getString("JIconCreatorPreview.title")); // NOI18N
        setBounds(new java.awt.Rectangle(0, 0, 1024, 600));
        setMaximumSize(new java.awt.Dimension(1024, 600));
        setMinimumSize(new java.awt.Dimension(700, 600));
        setName("previewDialog"); // NOI18N
        setPreferredSize(new java.awt.Dimension(700, 600));
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jLabelPreviewHidpiL.setText(bundle.getString("JIconCreatorPreview.jLabelPreviewHidpiL.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 15, 0, 0);
        getContentPane().add(jLabelPreviewHidpiL, gridBagConstraints);

        jLabelPreviewWebL.setText(bundle.getString("JIconCreatorPreview.jLabelPreviewWebL.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 30, 0, 0);
        getContentPane().add(jLabelPreviewWebL, gridBagConstraints);

        jLabelPreviewHdpiI.setText(bundle.getString("JIconCreatorPreview.jLabelPreviewHdpiI.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        getContentPane().add(jLabelPreviewHdpiI, gridBagConstraints);

        jLabelPreviewWebI.setText(bundle.getString("JIconCreatorPreview.jLabelPreviewWebI.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        getContentPane().add(jLabelPreviewWebI, gridBagConstraints);

        jButtonClosePreview.setText(bundle.getString("JIconCreatorPreview.jButtonClosePreview.text")); // NOI18N
        jButtonClosePreview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClosePreviewActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 30);
        getContentPane().add(jButtonClosePreview, gridBagConstraints);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonClosePreviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClosePreviewActionPerformed
        processWindowEvent(new WindowEvent(JIconCreatorPreview.this, WindowEvent.WINDOW_CLOSING));
    }//GEN-LAST:event_jButtonClosePreviewActionPerformed

    public void showPreviewDialog() {
        /* Display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        // Try to drop huge icons from memory.
                        System.gc();
                    }
                });
                setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonClosePreview;
    private javax.swing.JLabel jLabelPreviewHdpiI;
    private javax.swing.JLabel jLabelPreviewHidpiL;
    private javax.swing.JLabel jLabelPreviewWebI;
    private javax.swing.JLabel jLabelPreviewWebL;
    // End of variables declaration//GEN-END:variables
}
