/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ru.exlmoto.jiconcreator;

/**
 *
 * @author exl
 */
public class JIconCreator extends javax.swing.JFrame {

    /**
     * Creates new form JIconCreator
     */
    public JIconCreator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupScalingImage = new javax.swing.ButtonGroup();
        buttonGroupShapeImage = new javax.swing.ButtonGroup();
        buttonGroupScalingClipart = new javax.swing.ButtonGroup();
        buttonGroupShapeClipart = new javax.swing.ButtonGroup();
        jSplitPane = new javax.swing.JSplitPane();
        jPanelPreview = new javax.swing.JPanel();
        jLabelMdpiL = new javax.swing.JLabel();
        jLabelMdpiI = new javax.swing.JLabel();
        jLabelHdpiL = new javax.swing.JLabel();
        jLabelHdpiI = new javax.swing.JLabel();
        jLabelXhdpiL = new javax.swing.JLabel();
        jLabelXhdpiI = new javax.swing.JLabel();
        jLabelXxhdpiL = new javax.swing.JLabel();
        jLabelXxhdpiI = new javax.swing.JLabel();
        fillerLargeV1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        jPanelPreviewButton = new javax.swing.JPanel();
        fillerLargeH2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jButtonPreview = new javax.swing.JButton();
        fillerLargeH3 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jPanelGeneral = new javax.swing.JPanel();
        jTabbedPane = new javax.swing.JTabbedPane();
        jPanelImage = new javax.swing.JPanel();
        jLabelFileImage = new javax.swing.JLabel();
        jTextFieldPathImage = new javax.swing.JTextField();
        jButtonBrowseImage = new javax.swing.JButton();
        jButtonResetImage = new javax.swing.JButton();
        jLabelOptionsImage = new javax.swing.JLabel();
        jCheckBoxTrimImage = new javax.swing.JCheckBox();
        jLabelPaddingImage = new javax.swing.JLabel();
        jSliderPaddingImage = new javax.swing.JSlider();
        jLabelPercentsImage = new javax.swing.JLabel();
        jLabelScalingImage = new javax.swing.JLabel();
        jRadioButtonCropImage = new javax.swing.JRadioButton();
        jRadioButtonCenterImage = new javax.swing.JRadioButton();
        jLabelShapeImage = new javax.swing.JLabel();
        jRadioButtonNoneImage = new javax.swing.JRadioButton();
        jRadioButtonSquareImage = new javax.swing.JRadioButton();
        jRadioButtonCircleImage = new javax.swing.JRadioButton();
        jLabelBackgroundImage = new javax.swing.JLabel();
        jButtonColorImage = new javax.swing.JButton();
        jButtonRandomImage = new javax.swing.JButton();
        jLabelColorImage = new javax.swing.JLabel();
        jPanelText = new javax.swing.JPanel();
        jLabelClipart = new javax.swing.JLabel();
        jLabelOptionsClipart = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabelPaddingClipart = new javax.swing.JLabel();
        jSliderPaddingClipart = new javax.swing.JSlider();
        jLabelPercentsClipart = new javax.swing.JLabel();
        jLabelNameClipart = new javax.swing.JLabel();
        jLabelScalingClipart = new javax.swing.JLabel();
        jRadioButtonCropClipart = new javax.swing.JRadioButton();
        jRadioButtonCenterClipart = new javax.swing.JRadioButton();
        jLabelShapeClipart = new javax.swing.JLabel();
        jRadioButtonNoneClipart = new javax.swing.JRadioButton();
        jRadioButtonSquareClipart = new javax.swing.JRadioButton();
        jRadioButtonCircleClipart = new javax.swing.JRadioButton();
        jLabelColorClipartL = new javax.swing.JLabel();
        jButtonChooseClipartL = new javax.swing.JButton();
        jButtonRandomClipartL = new javax.swing.JButton();
        jLabelColorShowClipartL = new javax.swing.JLabel();
        jButtonChooseClipart = new javax.swing.JButton();
        jButtonResetClipart = new javax.swing.JButton();
        jLabelColorClipartH = new javax.swing.JLabel();
        jButtonChooseClipartH = new javax.swing.JButton();
        jButtonRandomClipartH = new javax.swing.JButton();
        jLabelColorShowClipartH = new javax.swing.JLabel();
        jPanelClipart = new javax.swing.JPanel();
        jPanelStatusBar = new javax.swing.JPanel();
        fillerSmallH1 = new javax.swing.Box.Filler(new java.awt.Dimension(3, 0), new java.awt.Dimension(3, 0), new java.awt.Dimension(3, 32767));
        jLabelStatusBar = new javax.swing.JLabel();
        fillerLargeH1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jButtonSave = new javax.swing.JButton();
        fillerSmallH2 = new javax.swing.Box.Filler(new java.awt.Dimension(3, 0), new java.awt.Dimension(3, 0), new java.awt.Dimension(3, 32767));
        jButtonSaveAs = new javax.swing.JButton();
        jMenuBar = new javax.swing.JMenuBar();
        jMenuFile = new javax.swing.JMenu();
        jMenuItemPreview = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItemSave = new javax.swing.JMenuItem();
        jMenuItemSaveAs = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItemExit = new javax.swing.JMenuItem();
        jMenuStyle = new javax.swing.JMenu();
        jMenuHelp = new javax.swing.JMenu();
        jMenuItemAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("Bundle"); // NOI18N
        setTitle(bundle.getString("JIconCreator.title")); // NOI18N
        setPreferredSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jSplitPane.setDividerLocation(550);

        jPanelPreview.setMinimumSize(new java.awt.Dimension(150, 500));
        jPanelPreview.setLayout(new javax.swing.BoxLayout(jPanelPreview, javax.swing.BoxLayout.PAGE_AXIS));

        jLabelMdpiL.setText(bundle.getString("JIconCreator.jLabelMdpiL.text")); // NOI18N
        jPanelPreview.add(jLabelMdpiL);

        jLabelMdpiI.setText(bundle.getString("JIconCreator.jLabelMdpiI.text")); // NOI18N
        jPanelPreview.add(jLabelMdpiI);

        jLabelHdpiL.setText(bundle.getString("JIconCreator.jLabelHdpiL.text")); // NOI18N
        jPanelPreview.add(jLabelHdpiL);

        jLabelHdpiI.setText(bundle.getString("JIconCreator.jLabelHdpiI.text")); // NOI18N
        jPanelPreview.add(jLabelHdpiI);

        jLabelXhdpiL.setText(bundle.getString("JIconCreator.jLabelXhdpiL.text")); // NOI18N
        jPanelPreview.add(jLabelXhdpiL);

        jLabelXhdpiI.setText(bundle.getString("JIconCreator.jLabelXhdpiI.text")); // NOI18N
        jPanelPreview.add(jLabelXhdpiI);

        jLabelXxhdpiL.setText(bundle.getString("JIconCreator.jLabelXxhdpiL.text")); // NOI18N
        jPanelPreview.add(jLabelXxhdpiL);

        jLabelXxhdpiI.setText(bundle.getString("JIconCreator.jLabelXxhdpiI.text")); // NOI18N
        jPanelPreview.add(jLabelXxhdpiI);
        jPanelPreview.add(fillerLargeV1);

        jPanelPreviewButton.setMaximumSize(new java.awt.Dimension(32767, 25));
        jPanelPreviewButton.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanelPreviewButton.setPreferredSize(new java.awt.Dimension(0, 30));
        jPanelPreviewButton.setLayout(new javax.swing.BoxLayout(jPanelPreviewButton, javax.swing.BoxLayout.LINE_AXIS));
        jPanelPreviewButton.add(fillerLargeH2);

        jButtonPreview.setText(bundle.getString("JIconCreator.jButtonPreview.text")); // NOI18N
        jPanelPreviewButton.add(jButtonPreview);
        jPanelPreviewButton.add(fillerLargeH3);

        jPanelPreview.add(jPanelPreviewButton);

        jSplitPane.setRightComponent(jPanelPreview);

        jPanelGeneral.setLayout(new javax.swing.BoxLayout(jPanelGeneral, javax.swing.BoxLayout.PAGE_AXIS));

        jLabelFileImage.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelFileImage.setText(bundle.getString("JIconCreator.jLabelFileImage.text")); // NOI18N
        jLabelFileImage.setMaximumSize(new java.awt.Dimension(78, 15));
        jLabelFileImage.setMinimumSize(new java.awt.Dimension(78, 15));
        jLabelFileImage.setPreferredSize(new java.awt.Dimension(78, 15));

        jTextFieldPathImage.setText(bundle.getString("JIconCreator.jTextFieldPathImage.text")); // NOI18N
        jTextFieldPathImage.setMinimumSize(new java.awt.Dimension(237, 25));
        jTextFieldPathImage.setPreferredSize(new java.awt.Dimension(237, 25));

        jButtonBrowseImage.setText(bundle.getString("JIconCreator.jButtonBrowseImage.text")); // NOI18N

        jButtonResetImage.setText(bundle.getString("JIconCreator.jButtonResetImage.text")); // NOI18N

        jLabelOptionsImage.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelOptionsImage.setText(bundle.getString("JIconCreator.jLabelOptionsImage.text")); // NOI18N
        jLabelOptionsImage.setMaximumSize(new java.awt.Dimension(78, 15));
        jLabelOptionsImage.setMinimumSize(new java.awt.Dimension(78, 15));
        jLabelOptionsImage.setPreferredSize(new java.awt.Dimension(78, 15));

        jCheckBoxTrimImage.setText(bundle.getString("JIconCreator.jCheckBoxTrimImage.text")); // NOI18N

        jLabelPaddingImage.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelPaddingImage.setText(bundle.getString("JIconCreator.jLabelPaddingImage.text")); // NOI18N
        jLabelPaddingImage.setMaximumSize(new java.awt.Dimension(78, 15));
        jLabelPaddingImage.setMinimumSize(new java.awt.Dimension(78, 15));
        jLabelPaddingImage.setPreferredSize(new java.awt.Dimension(78, 15));

        jLabelPercentsImage.setText(bundle.getString("JIconCreator.jLabelPercentsImage.text")); // NOI18N

        jLabelScalingImage.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelScalingImage.setText(bundle.getString("JIconCreator.jLabelScalingImage.text")); // NOI18N
        jLabelScalingImage.setMaximumSize(new java.awt.Dimension(78, 15));
        jLabelScalingImage.setMinimumSize(new java.awt.Dimension(78, 15));
        jLabelScalingImage.setPreferredSize(new java.awt.Dimension(78, 15));

        buttonGroupScalingImage.add(jRadioButtonCropImage);
        jRadioButtonCropImage.setText(bundle.getString("JIconCreator.jRadioButtonCropImage.text")); // NOI18N

        buttonGroupScalingImage.add(jRadioButtonCenterImage);
        jRadioButtonCenterImage.setText(bundle.getString("JIconCreator.jRadioButtonCenterImage.text")); // NOI18N

        jLabelShapeImage.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelShapeImage.setText(bundle.getString("JIconCreator.jLabelShapeImage.text")); // NOI18N
        jLabelShapeImage.setMaximumSize(new java.awt.Dimension(78, 15));
        jLabelShapeImage.setMinimumSize(new java.awt.Dimension(78, 15));
        jLabelShapeImage.setPreferredSize(new java.awt.Dimension(78, 15));

        buttonGroupShapeImage.add(jRadioButtonNoneImage);
        jRadioButtonNoneImage.setText(bundle.getString("JIconCreator.jRadioButtonNoneImage.text")); // NOI18N
        jRadioButtonNoneImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonNoneImageActionPerformed(evt);
            }
        });

        buttonGroupShapeImage.add(jRadioButtonSquareImage);
        jRadioButtonSquareImage.setText(bundle.getString("JIconCreator.jRadioButtonSquareImage.text")); // NOI18N

        buttonGroupShapeImage.add(jRadioButtonCircleImage);
        jRadioButtonCircleImage.setText(bundle.getString("JIconCreator.jRadioButtonCircleImage.text")); // NOI18N

        jLabelBackgroundImage.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelBackgroundImage.setText(bundle.getString("JIconCreator.jLabelBackgroundImage.text")); // NOI18N
        jLabelBackgroundImage.setMaximumSize(new java.awt.Dimension(78, 15));
        jLabelBackgroundImage.setMinimumSize(new java.awt.Dimension(78, 15));
        jLabelBackgroundImage.setPreferredSize(new java.awt.Dimension(78, 15));

        jButtonColorImage.setText(bundle.getString("JIconCreator.jButtonColorImage.text")); // NOI18N

        jButtonRandomImage.setText(bundle.getString("JIconCreator.jButtonRandomImage.text")); // NOI18N
        jButtonRandomImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRandomImageActionPerformed(evt);
            }
        });

        jLabelColorImage.setBackground(new java.awt.Color(255, 204, 0));
        jLabelColorImage.setText(bundle.getString("JIconCreator.jLabelColorImage.text")); // NOI18N
        jLabelColorImage.setMaximumSize(new java.awt.Dimension(25, 25));
        jLabelColorImage.setMinimumSize(new java.awt.Dimension(25, 25));
        jLabelColorImage.setOpaque(true);
        jLabelColorImage.setPreferredSize(new java.awt.Dimension(25, 25));

        javax.swing.GroupLayout jPanelImageLayout = new javax.swing.GroupLayout(jPanelImage);
        jPanelImage.setLayout(jPanelImageLayout);
        jPanelImageLayout.setHorizontalGroup(
            jPanelImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelImageLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelFileImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelOptionsImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPaddingImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelShapeImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelBackgroundImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelScalingImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelImageLayout.createSequentialGroup()
                        .addGroup(jPanelImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButtonCropImage)
                            .addComponent(jRadioButtonNoneImage))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelImageLayout.createSequentialGroup()
                                .addComponent(jRadioButtonSquareImage)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jRadioButtonCircleImage))
                            .addComponent(jRadioButtonCenterImage)))
                    .addGroup(jPanelImageLayout.createSequentialGroup()
                        .addComponent(jTextFieldPathImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonBrowseImage)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonResetImage))
                    .addGroup(jPanelImageLayout.createSequentialGroup()
                        .addComponent(jButtonColorImage)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonRandomImage)
                        .addGap(4, 4, 4)
                        .addComponent(jLabelColorImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelImageLayout.createSequentialGroup()
                        .addGroup(jPanelImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jSliderPaddingImage, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jCheckBoxTrimImage, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelPercentsImage)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelImageLayout.setVerticalGroup(
            jPanelImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelImageLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFileImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldPathImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBrowseImage)
                    .addComponent(jButtonResetImage))
                .addGap(18, 18, 18)
                .addGroup(jPanelImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelOptionsImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBoxTrimImage))
                .addGap(18, 18, 18)
                .addGroup(jPanelImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelPaddingImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSliderPaddingImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPercentsImage, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(18, 18, 18)
                .addGroup(jPanelImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonCropImage)
                    .addComponent(jRadioButtonCenterImage)
                    .addComponent(jLabelScalingImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelShapeImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButtonNoneImage)
                    .addComponent(jRadioButtonSquareImage)
                    .addComponent(jRadioButtonCircleImage))
                .addGap(18, 18, 18)
                .addGroup(jPanelImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelColorImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelBackgroundImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonColorImage)
                        .addComponent(jButtonRandomImage)))
                .addContainerGap(283, Short.MAX_VALUE))
        );

        jTabbedPane.addTab(bundle.getString("JIconCreator.jPanelImage.TabConstraints.tabTitle"), jPanelImage); // NOI18N

        jLabelClipart.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelClipart.setText(bundle.getString("JIconCreator.jLabelClipart.text")); // NOI18N
        jLabelClipart.setMaximumSize(new java.awt.Dimension(78, 15));
        jLabelClipart.setMinimumSize(new java.awt.Dimension(78, 15));
        jLabelClipart.setPreferredSize(new java.awt.Dimension(78, 15));

        jLabelOptionsClipart.setText(bundle.getString("JIconCreator.jLabelOptionsClipart.text")); // NOI18N

        jCheckBox1.setText(bundle.getString("JIconCreator.jCheckBox1.text")); // NOI18N
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jLabelPaddingClipart.setText(bundle.getString("JIconCreator.jLabelPaddingClipart.text")); // NOI18N

        jSliderPaddingClipart.setMinimumSize(new java.awt.Dimension(237, 16));
        jSliderPaddingClipart.setPreferredSize(new java.awt.Dimension(237, 16));

        jLabelPercentsClipart.setText(bundle.getString("JIconCreator.jLabelPercentsClipart.text")); // NOI18N

        jLabelNameClipart.setText(bundle.getString("JIconCreator.jLabelNameClipart.text")); // NOI18N

        jLabelScalingClipart.setText(bundle.getString("JIconCreator.jLabelScalingClipart.text")); // NOI18N

        buttonGroupScalingClipart.add(jRadioButtonCropClipart);
        jRadioButtonCropClipart.setText(bundle.getString("JIconCreator.jRadioButtonCropClipart.text")); // NOI18N

        buttonGroupScalingClipart.add(jRadioButtonCenterClipart);
        jRadioButtonCenterClipart.setText(bundle.getString("JIconCreator.jRadioButtonCenterClipart.text")); // NOI18N

        jLabelShapeClipart.setText(bundle.getString("JIconCreator.jLabelShapeClipart.text")); // NOI18N

        buttonGroupShapeClipart.add(jRadioButtonNoneClipart);
        jRadioButtonNoneClipart.setText(bundle.getString("JIconCreator.jRadioButtonNoneClipart.text")); // NOI18N

        buttonGroupShapeClipart.add(jRadioButtonSquareClipart);
        jRadioButtonSquareClipart.setText(bundle.getString("JIconCreator.jRadioButtonSquareClipart.text")); // NOI18N

        buttonGroupShapeClipart.add(jRadioButtonCircleClipart);
        jRadioButtonCircleClipart.setText(bundle.getString("JIconCreator.jRadioButtonCircleClipart.text")); // NOI18N

        jLabelColorClipartL.setText(bundle.getString("JIconCreator.jLabelColorClipartL.text")); // NOI18N

        jButtonChooseClipartL.setText(bundle.getString("JIconCreator.jButtonChooseClipartL.text")); // NOI18N

        jButtonRandomClipartL.setText(bundle.getString("JIconCreator.jButtonRandomClipartL.text")); // NOI18N

        jLabelColorShowClipartL.setBackground(new java.awt.Color(255, 204, 0));
        jLabelColorShowClipartL.setText(bundle.getString("JIconCreator.jLabelColorShowClipartL.text")); // NOI18N
        jLabelColorShowClipartL.setMaximumSize(new java.awt.Dimension(25, 25));
        jLabelColorShowClipartL.setMinimumSize(new java.awt.Dimension(25, 25));
        jLabelColorShowClipartL.setOpaque(true);
        jLabelColorShowClipartL.setPreferredSize(new java.awt.Dimension(25, 25));

        jButtonChooseClipart.setText(bundle.getString("JIconCreator.jButtonChooseClipart.text")); // NOI18N

        jButtonResetClipart.setText(bundle.getString("JIconCreator.jButtonResetClipart.text")); // NOI18N

        jLabelColorClipartH.setText(bundle.getString("JIconCreator.jLabelColorClipartH.text")); // NOI18N

        jButtonChooseClipartH.setText(bundle.getString("JIconCreator.jButtonChooseClipartH.text")); // NOI18N

        jButtonRandomClipartH.setText(bundle.getString("JIconCreator.jButtonRandomClipartH.text")); // NOI18N

        jLabelColorShowClipartH.setBackground(new java.awt.Color(255, 204, 0));
        jLabelColorShowClipartH.setText(bundle.getString("JIconCreator.jLabelColorShowClipartH.text")); // NOI18N
        jLabelColorShowClipartH.setMaximumSize(new java.awt.Dimension(25, 25));
        jLabelColorShowClipartH.setMinimumSize(new java.awt.Dimension(25, 25));
        jLabelColorShowClipartH.setOpaque(true);
        jLabelColorShowClipartH.setPreferredSize(new java.awt.Dimension(25, 25));

        javax.swing.GroupLayout jPanelTextLayout = new javax.swing.GroupLayout(jPanelText);
        jPanelText.setLayout(jPanelTextLayout);
        jPanelTextLayout.setHorizontalGroup(
            jPanelTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTextLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelColorClipartH)
                    .addComponent(jLabelColorClipartL)
                    .addComponent(jLabelShapeClipart)
                    .addComponent(jLabelScalingClipart)
                    .addComponent(jLabelPaddingClipart)
                    .addComponent(jLabelOptionsClipart)
                    .addComponent(jLabelClipart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelTextLayout.createSequentialGroup()
                        .addComponent(jLabelNameClipart)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonChooseClipart)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonResetClipart))
                    .addComponent(jCheckBox1)
                    .addGroup(jPanelTextLayout.createSequentialGroup()
                        .addComponent(jSliderPaddingClipart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelPercentsClipart))
                    .addGroup(jPanelTextLayout.createSequentialGroup()
                        .addComponent(jRadioButtonCropClipart)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButtonCenterClipart))
                    .addGroup(jPanelTextLayout.createSequentialGroup()
                        .addComponent(jRadioButtonNoneClipart)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonSquareClipart)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonCircleClipart))
                    .addGroup(jPanelTextLayout.createSequentialGroup()
                        .addGroup(jPanelTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelTextLayout.createSequentialGroup()
                                .addComponent(jButtonChooseClipartL)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonRandomClipartL))
                            .addGroup(jPanelTextLayout.createSequentialGroup()
                                .addComponent(jButtonChooseClipartH)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonRandomClipartH)))
                        .addGap(4, 4, 4)
                        .addGroup(jPanelTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelColorShowClipartH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelColorShowClipartL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(148, Short.MAX_VALUE))
        );
        jPanelTextLayout.setVerticalGroup(
            jPanelTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTextLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelClipart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNameClipart)
                    .addComponent(jButtonChooseClipart)
                    .addComponent(jButtonResetClipart))
                .addGap(18, 18, 18)
                .addGroup(jPanelTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelOptionsClipart)
                    .addComponent(jCheckBox1))
                .addGroup(jPanelTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTextLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabelPaddingClipart))
                    .addGroup(jPanelTextLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanelTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSliderPaddingClipart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelPercentsClipart))))
                .addGap(18, 18, 18)
                .addGroup(jPanelTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelScalingClipart)
                    .addComponent(jRadioButtonCropClipart)
                    .addComponent(jRadioButtonCenterClipart))
                .addGap(18, 18, 18)
                .addGroup(jPanelTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelShapeClipart)
                    .addComponent(jRadioButtonNoneClipart)
                    .addComponent(jRadioButtonSquareClipart)
                    .addComponent(jRadioButtonCircleClipart))
                .addGap(18, 18, 18)
                .addGroup(jPanelTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelColorShowClipartL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelColorClipartL)
                        .addComponent(jButtonChooseClipartL)
                        .addComponent(jButtonRandomClipartL)))
                .addGap(18, 18, 18)
                .addGroup(jPanelTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelColorClipartH)
                    .addComponent(jButtonChooseClipartH)
                    .addComponent(jButtonRandomClipartH)
                    .addComponent(jLabelColorShowClipartH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(240, Short.MAX_VALUE))
        );

        jTabbedPane.addTab(bundle.getString("JIconCreator.jPanelText.TabConstraints.tabTitle"), jPanelText); // NOI18N

        javax.swing.GroupLayout jPanelClipartLayout = new javax.swing.GroupLayout(jPanelClipart);
        jPanelClipart.setLayout(jPanelClipartLayout);
        jPanelClipartLayout.setHorizontalGroup(
            jPanelClipartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
        );
        jPanelClipartLayout.setVerticalGroup(
            jPanelClipartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 520, Short.MAX_VALUE)
        );

        jTabbedPane.addTab(bundle.getString("JIconCreator.jPanelClipart.TabConstraints.tabTitle"), jPanelClipart); // NOI18N

        jPanelGeneral.add(jTabbedPane);

        jPanelStatusBar.setMaximumSize(new java.awt.Dimension(800, 30));
        jPanelStatusBar.setMinimumSize(new java.awt.Dimension(400, 30));
        jPanelStatusBar.setPreferredSize(new java.awt.Dimension(550, 30));
        jPanelStatusBar.setLayout(new javax.swing.BoxLayout(jPanelStatusBar, javax.swing.BoxLayout.LINE_AXIS));
        jPanelStatusBar.add(fillerSmallH1);

        jLabelStatusBar.setText(bundle.getString("JIconCreator.jLabelStatusBar.text")); // NOI18N
        jPanelStatusBar.add(jLabelStatusBar);
        jPanelStatusBar.add(fillerLargeH1);

        jButtonSave.setText(bundle.getString("JIconCreator.jButtonSave.text")); // NOI18N
        jPanelStatusBar.add(jButtonSave);
        jPanelStatusBar.add(fillerSmallH2);

        jButtonSaveAs.setText(bundle.getString("JIconCreator.jButtonSaveAs.text")); // NOI18N
        jPanelStatusBar.add(jButtonSaveAs);

        jPanelGeneral.add(jPanelStatusBar);

        jSplitPane.setLeftComponent(jPanelGeneral);

        getContentPane().add(jSplitPane);

        jMenuFile.setText(bundle.getString("JIconCreator.jMenuFile.text")); // NOI18N

        jMenuItemPreview.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemPreview.setText(bundle.getString("JIconCreator.jMenuItemPreview.text")); // NOI18N
        jMenuFile.add(jMenuItemPreview);
        jMenuFile.add(jSeparator1);

        jMenuItemSave.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemSave.setText(bundle.getString("JIconCreator.jMenuItemSave.text")); // NOI18N
        jMenuFile.add(jMenuItemSave);

        jMenuItemSaveAs.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemSaveAs.setText(bundle.getString("JIconCreator.jMenuItemSaveAs.text")); // NOI18N
        jMenuFile.add(jMenuItemSaveAs);
        jMenuFile.add(jSeparator2);

        jMenuItemExit.setText(bundle.getString("JIconCreator.jMenuItemExit.text")); // NOI18N
        jMenuFile.add(jMenuItemExit);

        jMenuBar.add(jMenuFile);

        jMenuStyle.setText(bundle.getString("JIconCreator.jMenuStyle.text")); // NOI18N
        jMenuBar.add(jMenuStyle);

        jMenuHelp.setText(bundle.getString("JIconCreator.jMenuHelp.text")); // NOI18N

        jMenuItemAbout.setText(bundle.getString("JIconCreator.jMenuItemAbout.text")); // NOI18N
        jMenuHelp.add(jMenuItemAbout);

        jMenuBar.add(jMenuHelp);

        setJMenuBar(jMenuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JIconCreator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JIconCreator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JIconCreator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JIconCreator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JIconCreator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupScalingClipart;
    private javax.swing.ButtonGroup buttonGroupScalingImage;
    private javax.swing.ButtonGroup buttonGroupShapeClipart;
    private javax.swing.ButtonGroup buttonGroupShapeImage;
    private javax.swing.Box.Filler fillerLargeH1;
    private javax.swing.Box.Filler fillerLargeH2;
    private javax.swing.Box.Filler fillerLargeH3;
    private javax.swing.Box.Filler fillerLargeV1;
    private javax.swing.Box.Filler fillerSmallH1;
    private javax.swing.Box.Filler fillerSmallH2;
    private javax.swing.JButton jButtonBrowseImage;
    private javax.swing.JButton jButtonChooseClipart;
    private javax.swing.JButton jButtonChooseClipartH;
    private javax.swing.JButton jButtonChooseClipartL;
    private javax.swing.JButton jButtonColorImage;
    private javax.swing.JButton jButtonPreview;
    private javax.swing.JButton jButtonRandomClipartH;
    private javax.swing.JButton jButtonRandomClipartL;
    private javax.swing.JButton jButtonRandomImage;
    private javax.swing.JButton jButtonResetClipart;
    private javax.swing.JButton jButtonResetImage;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JButton jButtonSaveAs;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBoxTrimImage;
    private javax.swing.JLabel jLabelBackgroundImage;
    private javax.swing.JLabel jLabelClipart;
    private javax.swing.JLabel jLabelColorClipartH;
    private javax.swing.JLabel jLabelColorClipartL;
    private javax.swing.JLabel jLabelColorImage;
    private javax.swing.JLabel jLabelColorShowClipartH;
    private javax.swing.JLabel jLabelColorShowClipartL;
    private javax.swing.JLabel jLabelFileImage;
    private javax.swing.JLabel jLabelHdpiI;
    private javax.swing.JLabel jLabelHdpiL;
    private javax.swing.JLabel jLabelMdpiI;
    private javax.swing.JLabel jLabelMdpiL;
    private javax.swing.JLabel jLabelNameClipart;
    private javax.swing.JLabel jLabelOptionsClipart;
    private javax.swing.JLabel jLabelOptionsImage;
    private javax.swing.JLabel jLabelPaddingClipart;
    private javax.swing.JLabel jLabelPaddingImage;
    private javax.swing.JLabel jLabelPercentsClipart;
    private javax.swing.JLabel jLabelPercentsImage;
    private javax.swing.JLabel jLabelScalingClipart;
    private javax.swing.JLabel jLabelScalingImage;
    private javax.swing.JLabel jLabelShapeClipart;
    private javax.swing.JLabel jLabelShapeImage;
    private javax.swing.JLabel jLabelStatusBar;
    private javax.swing.JLabel jLabelXhdpiI;
    private javax.swing.JLabel jLabelXhdpiL;
    private javax.swing.JLabel jLabelXxhdpiI;
    private javax.swing.JLabel jLabelXxhdpiL;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenu jMenuFile;
    private javax.swing.JMenu jMenuHelp;
    private javax.swing.JMenuItem jMenuItemAbout;
    private javax.swing.JMenuItem jMenuItemExit;
    private javax.swing.JMenuItem jMenuItemPreview;
    private javax.swing.JMenuItem jMenuItemSave;
    private javax.swing.JMenuItem jMenuItemSaveAs;
    private javax.swing.JMenu jMenuStyle;
    private javax.swing.JPanel jPanelClipart;
    private javax.swing.JPanel jPanelGeneral;
    private javax.swing.JPanel jPanelImage;
    private javax.swing.JPanel jPanelPreview;
    private javax.swing.JPanel jPanelPreviewButton;
    private javax.swing.JPanel jPanelStatusBar;
    private javax.swing.JPanel jPanelText;
    private javax.swing.JRadioButton jRadioButtonCenterClipart;
    private javax.swing.JRadioButton jRadioButtonCenterImage;
    private javax.swing.JRadioButton jRadioButtonCircleClipart;
    private javax.swing.JRadioButton jRadioButtonCircleImage;
    private javax.swing.JRadioButton jRadioButtonCropClipart;
    private javax.swing.JRadioButton jRadioButtonCropImage;
    private javax.swing.JRadioButton jRadioButtonNoneClipart;
    private javax.swing.JRadioButton jRadioButtonNoneImage;
    private javax.swing.JRadioButton jRadioButtonSquareClipart;
    private javax.swing.JRadioButton jRadioButtonSquareImage;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JSlider jSliderPaddingClipart;
    private javax.swing.JSlider jSliderPaddingImage;
    private javax.swing.JSplitPane jSplitPane;
    private javax.swing.JTabbedPane jTabbedPane;
    private javax.swing.JTextField jTextFieldPathImage;
    // End of variables declaration//GEN-END:variables
}
